/*
 * conform.h — the C ABI of `conform-ffi`.
 *
 * GENERATED by cbindgen from crates/conform-ffi/src. Do not edit by hand:
 * `crates/conform-ffi/tests/the_header_matches_the_library.rs` regenerates
 * this file and fails if it differs from the committed copy, so an edit here
 * is an edit that will be reverted by CI rather than one that will be kept.
 *
 * To change it, change the Rust and run:
 *
 *     cargo test -p conform-ffi --features header-check
 *
 * which prints the difference, then re-run with CONFORM_UPDATE_HEADER=1 to
 * write it.
 *
 * SPDX-License-Identifier: MIT OR Apache-2.0
 */


#ifndef CONFORM_H
#define CONFORM_H



#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The version of the **ABI** — the function signatures, the status codes and
 * the ownership rules, not the library and not the JSON.
 *
 * Emitted into `conform.h` as a compile-time constant so that a binding can
 * refuse a library it was not written against. It changes only when an
 * existing signature or an existing status code changes meaning; adding a
 * function or appending a status code does not move it, because neither
 * breaks a caller that does not use them.
 *
 * The other two numbers a consumer may want are `conform_version()`, which is
 * this library's release version, and `CONFORM_SCHEMA_VERSION`, which is the
 * shape of the JSON that comes back.
 */
#define CONFORM_ABI_VERSION 1

/**
 * The version of the envelope below.
 *
 * Bumped when a field is removed or changes meaning; **not** bumped when one
 * is added, because adding is what the JSON boundary exists to make cheap.
 * A consumer should refuse a `schema_version` it does not know.
 */
#define CONFORM_SCHEMA_VERSION 1

/**
 * The outcome of a call across the boundary.
 *
 * `0` is success. Every other value is a failure of the call itself, and
 * leaves a human-readable explanation in `conform_last_error`.
 */
enum ConformStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The call did what it was asked. For a validation this means a report
     * was produced — **not** that the document conformed.
     */
    CONFORM_STATUS_OK = 0,
    /**
     * A pointer the call cannot do without was null.
     */
    CONFORM_STATUS_NULL_POINTER = 1,
    /**
     * A handle was not one: it failed the guard word every validator carries.
     *
     * The guard catches null, misaligned, zeroed or freed handles. It cannot
     * catch a pointer into memory the process has not mapped; nothing can.
     */
    CONFORM_STATUS_INVALID_HANDLE = 2,
    /**
     * A string argument was not valid UTF-8, or a C string was not
     * terminated within the bounds the caller gave.
     */
    CONFORM_STATUS_INVALID_UTF8 = 3,
    /**
     * The spec id names no adapter this library can build.
     */
    CONFORM_STATUS_UNKNOWN_SPEC = 4,
    /**
     * The registry could not be loaded, or the vendored schema behind the
     * requested spec failed its provenance check.
     *
     * The diagnostics explaining it are in the last-error string.
     */
    CONFORM_STATUS_REGISTRY = 5,
    /**
     * The report could not be serialised, or held a NUL byte and so could not
     * be handed over as a C string.
     */
    CONFORM_STATUS_SERIALISATION = 6,
    /**
     * A panic was caught at the boundary and did not cross it.
     *
     * Always a bug in this library. Reported rather than aborted because an
     * unwind through a C frame is undefined behaviour and a returned code is
     * not.
     */
    CONFORM_STATUS_PANIC = 7,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ConformStatus ConformStatus;
#else
typedef int32_t ConformStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * An opaque handle to a built validator.
 *
 * Created by `conform_validator_new`, released by `conform_validator_free`,
 * and meaningful to nothing else. Its layout is deliberately not part of the
 * ABI: a caller only ever holds a pointer to one, and only this library ever
 * follows it.
 */
typedef struct ConformValidator ConformValidator;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The version of this library, as a NUL-terminated UTF-8 string.
 *
 * Static storage. The caller must **not** free it, and it is valid for the
 * life of the process.
 *
 * This is the *library's* version and moves when the crate is released. The
 * version of the **ABI** is the compile-time constant `CONFORM_ABI_VERSION`
 * in this header, and the version of the JSON a validation returns is the
 * `schema_version` field inside it. They are three different numbers because
 * they answer three different questions.
 */
const char *conform_version(void);

/**
 * Build a validator for one specification.
 *
 * `spec_id` is a registry identifier — `"odcs"` or `"odps"`. `registry_path`
 * is the path to a `specs.toml`; it is **required**, because this library
 * does not go looking through an embedder's filesystem for one. The schema
 * behind the entry is re-hashed against the digest the registry records
 * before the validator is handed back, so a drifted schema is a failure here
 * rather than a quiet verdict later.
 *
 * Returns null on failure, with the reason in `conform_last_error`.
 * Release the handle with `conform_validator_free`.
 *
 * # Safety
 *
 * Both arguments must either be null or point at NUL-terminated byte
 * strings, and must stay readable for the duration of the call. Nothing is
 * borrowed beyond it.
 */
struct ConformValidator *conform_validator_new(const char *spec_id, const char *registry_path);

/**
 * Validate one document and return the report as JSON.
 *
 * `document` and `document_len` are the document's bytes; they must be UTF-8
 * and need not be NUL-terminated. `document` may be null only when
 * `document_len` is zero. `document_id` is the name the findings will locate
 * themselves by — a path, a URL, or anything else meaningful to the caller.
 *
 * On success `*out_json` receives a NUL-terminated UTF-8 JSON string owned by
 * this library; release it with `conform_string_free`. If `out_len` is not
 * null it receives the string's length in bytes, excluding the NUL, so a
 * caller need not walk it. On failure `*out_json` is set to null and
 * `*out_len`, if given, to zero.
 *
 * **A document full of errors is a success.** The return value says whether a
 * report was produced; what the report says is in the JSON. Reporting and
 * gating are separate decisions in this family, and this boundary does not
 * gate at all — the caller applies whatever policy it has to the severities
 * it reads.
 *
 * The JSON is JSON-encoded and is **not** escaped for a terminal. A message
 * quotes the document verbatim, so it can carry a bidirectional override or
 * an ANSI sequence; neutralising that is the job of whatever displays it, and
 * doing it here as well would corrupt the data.
 *
 * # Safety
 *
 * `validator` must be a live handle from `conform_validator_new` that no
 * other thread is using concurrently. `document_id` must be a NUL-terminated
 * byte string. `document` must be readable for `document_len` bytes.
 * `out_json` must be a writable pointer to a `char*`, and `out_len`, if not
 * null, a writable pointer to a `size_t`.
 */
ConformStatus conform_validate(struct ConformValidator *validator,
                               const char *document_id,
                               const uint8_t *document,
                               size_t document_len,
                               char **out_json,
                               size_t *out_len);

/**
 * Why the last call on **this thread** failed, or null if it did not.
 *
 * The string is owned by this library and must not be freed. It is valid
 * until the next call into this library on the same thread, and until the
 * thread exits; copy it if you need it for longer. This is `strerror`'s
 * contract, deliberately.
 */
const char *conform_last_error(void);

/**
 * Release a string this library returned.
 *
 * Null is accepted and does nothing, so a caller can free unconditionally.
 *
 * # Safety
 *
 * `text` must be null, or a pointer this library returned through `out_json`
 * and has not already taken back. Freeing anything else, or the same pointer
 * twice, is undefined behaviour that no guard word can catch: the allocation
 * carries no header this library controls.
 */
void conform_string_free(char *text);

/**
 * Release a validator handle.
 *
 * Null is accepted and does nothing. The guard word is poisoned before the
 * allocation is released, so a subsequent call with the same pointer is
 * *likely* — not certainly; see this module's documentation — to be refused
 * with `CONFORM_STATUS_INVALID_HANDLE` rather than to be undefined.
 *
 * # Safety
 *
 * `validator` must be null, or a live handle from `conform_validator_new`
 * that has not already been freed and that no other thread is using.
 */
void conform_validator_free(struct ConformValidator *validator);

/**
 * Prove that a panic inside this library cannot escape it.
 *
 * Panics on purpose, catches it, and returns `CONFORM_STATUS_PANIC`. A
 * binding should call this once at start-up: getting that code back is proof
 * that the library it linked was built with unwinding and that the net under
 * every other entry point is real. A process that *dies* here has linked a
 * `panic = "abort"` build, in which case no entry point in this library is
 * safe to call from C and the only fix is to rebuild it.
 *
 * It writes a message to `stderr` on the way past, because that is what a
 * Rust panic does and suppressing it would mean installing a process-global
 * panic hook from a library, which is not this library's to install.
 *
 * # Panics
 *
 * It panics deliberately, and catches it. Nothing escapes; if something
 * did, the message in this section would be the last thing the host
 * process read, which is the whole reason this function exists.
 */
ConformStatus conform_self_test_panic(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CONFORM_H */
