// `#[wasm_bindgen]` expands to `unsafe` — the exported shims, the describe
// hooks and the ABI conversions are all generated code, and none of it is
// written here. The crate's manifest sets `unsafe_code = "deny"` rather than
// the workspace's `forbid` so that the opt-out has to be written at the item
// that takes it; [`crate::abi`] is the other one, and it is the only one that
// contains hand-written `unsafe`.
#![allow(
    unsafe_code,
    reason = "every unsafe item in this module is generated by #[wasm_bindgen]; \
              no line of it is hand-written, and the module contains no raw \
              pointer of its own"
)]

//! A `wasm-bindgen` binding, and an honest account of what it cannot promise.
//!
//! Optional, behind the `wasm` feature, and additive in the strict sense: with
//! the feature off this module does not exist, `wasm-bindgen` is not in the
//! tree, and [`crate::abi`] is unchanged.
//! `tests/the_wasm_feature_is_additive.rs` measures that rather than asserting
//! it.
//!
//! # The panic contract, which is *not* the C ABI's
//!
//! This is the part to read before anything else.
//!
//! [`crate::abi`] promises that no panic crosses the boundary: every
//! `extern "C"` entry point wraps its body in [`std::panic::catch_unwind`],
//! and [`crate::abi::conform_self_test_panic`] exists so a caller can prove
//! the net is really there. **On `wasm32-unknown-unknown` that promise is
//! false, and this module does not make it.**
//!
//! The target is `panic = "abort"`. There is no unwinding, so `catch_unwind`
//! has nothing to catch; the panic becomes an `unreachable` trap and the call
//! throws `RuntimeError: unreachable` in the host. The only dishonest thing
//! available here would be to wrap the calls below in a `catch_unwind` that
//! cannot fire and let a reader infer a net from its presence.
//!
//! **The instance is not poisoned, and that is the dangerous part.** This was
//! measured rather than assumed — `tools/wasm/probe.mjs` traps on purpose and
//! then calls back in — and after the trap `conformVersion()` still answers
//! and a fresh validator still builds. WebAssembly does not stop an instance
//! that traps. What died is everything the panicking call was half-way
//! through: no destructor ran, no allocation was released, no invariant was
//! restored, and nothing anywhere reports that. A host that keeps using the
//! instance is using one whose internal state was abandoned mid-edit, and it
//! will not be told.
//!
//! So the contract is: **a panic inside this module is fatal to the instance,
//! whether or not the instance notices. Discard it and build another.** A
//! host that cares should run this module in a worker it can throw away, and
//! must treat a thrown `RuntimeError: unreachable` as "this instance is gone"
//! rather than as "that document failed".
//!
//! Two things make that structural rather than a doc comment somebody can skip:
//!
//! 1. **There is no `selfTestPanic` here.** The C ABI's self-test returns
//!    `CONFORM_STATUS_PANIC` to prove a panic was caught. Exporting a function
//!    with that shape from a target where nothing can be caught would be
//!    exporting a claim. It is absent, and its absence is the point.
//! 2. **[`panic_contract`] is what the host displays.** The string a page
//!    shows about panics comes out of the compiled artefact, so it cannot be
//!    edited into something friendlier without editing the module that
//!    behaves that way. [`demonstrate_panic_is_fatal`] is the executable
//!    version: it panics, it does not return, and a caller who wants the proof
//!    rather than the sentence can have it — once, per instance.
//!
//! # No filesystem, and no bytes from JavaScript
//!
//! `conform_validator_new` takes a registry path, and a browser has no
//! filesystem to resolve one against. The fix is *not* a constructor that
//! takes schema bytes from the page: that hands the provenance decision to the
//! caller and reduces this repository's digest check to decoration. The schema
//! and the registry are frozen into the artefact instead and the digest is
//! re-checked here at construction — see [`crate::embedded`] for the argument
//! in full, and for what that check cannot cover.
//!
//! A caller therefore names a **spec id**, never a schema.
//!
//! # From JavaScript
//!
//! ```js
//! import init, { ConformValidator, conformVersion, panicContract }
//!     from "./conform_ffi.js";
//!
//! await init();
//! console.log(conformVersion(), panicContract());
//!
//! const validator = new ConformValidator("odcs");
//! const report = JSON.parse(validator.validate("orders.yaml", text));
//! console.log(report.document.worst_severity, report.diagnostics);
//! validator.free();
//! ```
//!
//! `free()` is `wasm-bindgen`'s, not this crate's: the handle owns a compiled
//! JSON Schema in linear memory, and a page that builds one per keystroke and
//! never frees will grow the heap until the instance dies. There is no
//! `conform_string_free` here — the JSON crosses as a JavaScript string that
//! the host's garbage collector owns.

use wasm_bindgen::JsError;
use wasm_bindgen::prelude::wasm_bindgen;

use crate::embedded;
use crate::engine::Backend;

/// What happens when this module panics, in one sentence a host can display.
///
/// A constant rather than prose in a page, so that the claim and the behaviour
/// ship in the same artefact. See this module's documentation.
pub const PANIC_CONTRACT: &str = "A panic in this module is fatal to the WebAssembly instance. The target is \
     `panic = \"abort\"`, so there is no unwinding for `catch_unwind` to catch: the panic \
     becomes an `unreachable` trap and the call throws a RuntimeError. WebAssembly does not \
     stop the instance — later calls may well answer, and that is the danger, because \
     whatever the panicking call was half-way through was abandoned with no destructor run \
     and nothing to report it. Discard the instance and build another. The C ABI's \
     guarantee that no panic crosses the boundary is a NATIVE guarantee and is not claimed \
     here.";

/// This library's version.
///
/// The same string `conform_version()` returns across the C ABI, as a
/// JavaScript string rather than a pointer into linear memory.
#[wasm_bindgen(js_name = conformVersion)]
#[must_use]
pub fn conform_version() -> String {
    env!("CARGO_PKG_VERSION").to_owned()
}

/// The version of the JSON envelope [`ConformValidator::validate`] returns.
///
/// A consumer should refuse a `schema_version` it does not know; this is how
/// it finds out what it is about to be handed.
#[wasm_bindgen(js_name = envelopeSchemaVersion)]
#[must_use]
pub fn envelope_schema_version() -> u32 {
    crate::report::SCHEMA_VERSION
}

/// What happens when this module panics. See [`PANIC_CONTRACT`].
///
/// Exported so that a page states the contract in the artefact's own words. A
/// host that renders its own sentence about panics is a host whose sentence
/// can stop being true without anything failing to build.
#[wasm_bindgen(js_name = panicContract)]
#[must_use]
pub fn panic_contract() -> String {
    PANIC_CONTRACT.to_owned()
}

/// The spec ids this build can validate, read from what is actually embedded
/// in it.
///
/// Computed from [`crate::embedded::EMBEDDED`] rather than listed again, so a
/// page cannot offer a standard this artefact does not carry the schema for.
#[wasm_bindgen(js_name = reachableSpecIds)]
#[must_use]
pub fn reachable_spec_ids() -> Vec<String> {
    embedded::spec_ids()
        .into_iter()
        .map(ToOwned::to_owned)
        .collect()
}

/// Panic on purpose, to demonstrate that a panic here is fatal.
///
/// **This function does not return.** It traps with `unreachable` and the call
/// throws `RuntimeError: unreachable` in the host. The instance keeps
/// answering afterwards — that was measured, see [`PANIC_CONTRACT`] — which is
/// precisely why a host must not read a successful later call as evidence that
/// the panic was survivable.
///
/// It is the counterpart of [`crate::abi::conform_self_test_panic`] and
/// deliberately not the equivalent of it. That one returns
/// `CONFORM_STATUS_PANIC`, which is a claim that the panic was caught; this
/// one returns nothing, ever, which is the claim that is true here. A caller
/// that wants the proof rather than the sentence in [`PANIC_CONTRACT`] can
/// call it — in an instance it is willing to lose.
///
/// # Panics
///
/// Always, immediately, and nothing catches it. That is the demonstration.
#[wasm_bindgen(js_name = demonstratePanicIsFatal)]
pub fn demonstrate_panic_is_fatal() {
    panic!(
        "deliberate panic from demonstrate_panic_is_fatal: nothing caught this, no destructor \
         ran, and whatever this instance was doing was abandoned where it stood — discard it"
    );
}

/// A validator for one specification, built from the bytes frozen into this
/// artefact.
///
/// Construction is where the schema's digest is re-checked against the
/// embedded registry; a handle that exists is a handle that earned the right
/// to issue verdicts. Release it with `free()` when the page is done with it.
#[wasm_bindgen(js_name = ConformValidator)]
#[derive(Debug)]
pub struct ConformValidator {
    backend: Backend,
}

#[wasm_bindgen(js_class = ConformValidator)]
impl ConformValidator {
    /// Build a validator for `spec_id` — `"odcs"` or `"odps"`.
    ///
    /// The schema is the one compiled into this build, and its bytes are
    /// re-hashed against the digest the embedded `specs.toml` records for them
    /// before anything is compiled. There is no way to pass a schema in, on
    /// purpose: see [`crate::embedded`].
    ///
    /// # Errors
    ///
    /// Throws with the registry's own diagnostics — codes and all, not a
    /// paraphrase — if the id names nothing embedded here, if the embedded
    /// registry will not parse, or if the embedded bytes no longer hash to the
    /// digest recorded for them.
    #[wasm_bindgen(constructor)]
    pub fn new(spec_id: &str) -> Result<ConformValidator, JsError> {
        embedded::build(spec_id)
            .map(|backend| Self { backend })
            .map_err(|error| JsError::new(error.message()))
    }

    /// Which standard this validator speaks for.
    #[wasm_bindgen(getter, js_name = specId)]
    #[must_use]
    pub fn spec_id(&self) -> String {
        self.backend.spec().id
    }

    /// The version of that standard, when the registry recorded one.
    #[wasm_bindgen(getter, js_name = specVersion)]
    #[must_use]
    pub fn spec_version(&self) -> Option<String> {
        self.backend.spec().version
    }

    /// Validate one document and return the report as a JSON string.
    ///
    /// `document_id` is the name the findings locate themselves by.
    /// `text` is the document.
    ///
    /// **A document full of errors is a success.** This call throws only when
    /// no report could be produced at all; what the report says is in the
    /// JSON, and the caller applies whatever policy it has to the severities
    /// it reads. That is the same rule the C ABI follows and the same rule
    /// `conform validate` follows.
    ///
    /// The JSON is JSON-encoded and is **not** escaped for a terminal or for
    /// HTML. A message quotes the document verbatim, so it can carry a
    /// bidirectional override or an ANSI sequence; neutralising that is the
    /// job of whatever displays it — in a browser, that means setting
    /// `textContent` rather than `innerHTML` — and doing it here as well would
    /// corrupt the data.
    ///
    /// # Errors
    ///
    /// Throws if the report cannot be serialised, which for this shape means
    /// an allocation failure. It is returned rather than unwrapped because on
    /// this target an unwrap is an instance-killing trap.
    pub fn validate(&self, document_id: &str, text: &str) -> Result<String, JsError> {
        self.backend
            .validate_to_json(document_id, text)
            .map_err(|error| JsError::new(&format!("the report could not be serialised: {error}")))
    }

    /// The sentence every report from this validator carries about where its
    /// schema came from.
    ///
    /// Worth showing next to a verdict: it says the bytes were embedded and
    /// re-hashed, and it says what that check cannot speak for.
    #[wasm_bindgen(getter)]
    #[must_use]
    pub fn provenance(&self) -> String {
        match &self.backend {
            Backend::Odcs(validator) => validator.provenance().to_owned(),
            Backend::Odps(validator) => validator.provenance().to_owned(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // These run on the host, not in a browser. What they can check is the
    // logic behind the binding — that a validator builds, that it reports,
    // that the contract string says what the module does. Two things they
    // cannot: the trap, because on an unwinding host the panic above is
    // caught by the test harness rather than fatal; and anything that
    // constructs a `JsError`, because that is a JavaScript object and
    // `wasm-bindgen` panics rather than fake one here. Both are what
    // `tools/wasm/probe.mjs` is for, and why it is a runnable thing rather
    // than a claim in this file.

    #[test]
    fn a_validator_builds_for_every_embedded_spec_and_reports() {
        for spec_id in embedded::spec_ids() {
            let validator = ConformValidator::new(spec_id)
                .unwrap_or_else(|_| panic!("`{spec_id}` did not build"));
            assert_eq!(validator.spec_id(), spec_id);
            assert!(validator.provenance().contains("embedded"));

            let json = validator
                .validate("empty.yaml", "")
                .expect("an empty document still produces a report");
            let parsed: serde_json::Value = serde_json::from_str(&json).expect("valid JSON");
            assert_eq!(parsed["schema_version"], envelope_schema_version());
            assert_eq!(parsed["spec"]["id"], spec_id);
            assert_eq!(parsed["document"]["id"], "empty.yaml");
        }
    }

    #[test]
    fn an_unembedded_spec_id_is_refused_before_a_handle_exists() {
        // Asserted at the seam that produces the refusal rather than through
        // the constructor, because `JsError` is a JavaScript object:
        // `wasm-bindgen` panics rather than fabricate one off a wasm target,
        // so the error arm of `new` cannot be reached on the host at all.
        // `new` is a `map`/`map_err` over exactly this call and makes no
        // decision of its own; `tools/wasm/probe.mjs` exercises the thrown
        // side of it in a real instance.
        assert!(embedded::build("okf").is_err());
        assert!(embedded::build("nonsense").is_err());
    }

    #[test]
    fn the_reachable_ids_are_the_embedded_ones() {
        assert_eq!(reachable_spec_ids(), vec!["odcs", "odps"]);
    }

    #[test]
    fn the_panic_contract_does_not_claim_a_net() {
        let contract = panic_contract();
        assert!(contract.contains("fatal"), "{contract}");
        assert!(contract.contains("Discard the instance"), "{contract}");
        // It must not claim the instance stops, because it does not — see the
        // measurement `tools/wasm/probe.mjs` takes.
        assert!(
            contract.contains("later calls may well answer"),
            "{contract}"
        );
        // And the C ABI's claim has to be named as native-only, not repeated.
        assert!(contract.contains("NATIVE"), "{contract}");
    }

    #[test]
    fn the_version_is_this_crate_s() {
        assert_eq!(conform_version(), env!("CARGO_PKG_VERSION"));
    }
}
