#!/bin/sh
# Build the Open Spec Conform site into website/dist.
#
# The site is a build-output of the registry: `conform-web` reads `specs.toml`
# and the member manifests and renders one HTML file. There is no node, no npm,
# no bundler and no lockfile outside `Cargo.lock` — the page is generated by a
# workspace crate, which is what lets the catalogue be a function of the
# registry rather than a transcription of it.
#
# Two steps, and the first is allowed to fail. `tools/wasm/build.sh` compiles
# `conform-ffi`'s WebAssembly binding into `website/dist/wasm`, which is what
# the page's in-browser validator loads. It needs the `wasm32-unknown-unknown`
# target and the `wasm-bindgen` CLI, and a build environment may have neither.
#
# So its failure is not this script's failure. `conform-web` looks for the
# artefacts, finds nothing, and renders a page that says there is no demo and
# which files it went looking for — `conform_web::site::Demo` is a typed value
# precisely so that the page cannot claim a capability this build lacks. A
# missing module costs a reader the validation box and nothing else; a site
# that failed to deploy over it would cost them the catalogue too.
#
# This follows `roteiro/website/build.sh`, which is the house precedent for a
# site generated by its own repository's Rust binary. The workspace MSRV is
# 1.96, and build environments whose default toolchain is older — or which ship
# no Rust at all — are handled by bootstrapping the pinned toolchain here, so a
# Git-integration deploy needs no dashboard configuration.
set -eu
cd "$(dirname "$0")/.."

MSRV=1.96
if command -v rustup >/dev/null 2>&1; then
  rustup toolchain install "$MSRV" --profile minimal 2>/dev/null || true
  CARGO="cargo +$MSRV"
elif command -v cargo >/dev/null 2>&1; then
  CARGO="cargo"
else
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | sh -s -- -y --profile minimal --default-toolchain "$MSRV"
  . "$HOME/.cargo/env"
  CARGO="cargo +$MSRV"
fi

# 1. The validator, compiled to WebAssembly. Allowed to fail; see above.
if ! tools/wasm/build.sh --target web --out website/dist/wasm; then
  echo "website/build.sh: no WebAssembly module was built; the page will say so" >&2
  rm -rf website/dist/wasm
fi

# 2. The page. `--wasm` is where it looks for what step 1 may or may not have
#    produced, and a missing module is a sentence on the page rather than an
#    error here.
$CARGO run --quiet --package conform-web -- \
  --root . --out website/dist --wasm website/dist/wasm
