#!/bin/sh
# Build the Open Spec Conform site into website/dist.
#
# The site is a build-output of the registry: `conform-web` reads `specs.toml`
# and the member manifests and renders one self-contained HTML file. There is
# no node, no npm, no bundler and no lockfile outside `Cargo.lock` — the page
# is generated by a workspace crate, which is what lets the catalogue be a
# function of the registry rather than a transcription of it.
#
# This follows `roteiro/website/build.sh`, which is the house precedent for a
# site generated by its own repository's Rust binary. The workspace MSRV is
# 1.96, and build environments whose default toolchain is older — or which ship
# no Rust at all — are handled by bootstrapping the pinned toolchain here, so a
# Git-integration deploy needs no dashboard configuration.
set -eu
cd "$(dirname "$0")/.."

MSRV=1.96
if command -v rustup >/dev/null 2>&1; then
  rustup toolchain install "$MSRV" --profile minimal 2>/dev/null || true
  CARGO="cargo +$MSRV"
elif command -v cargo >/dev/null 2>&1; then
  CARGO="cargo"
else
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | sh -s -- -y --profile minimal --default-toolchain "$MSRV"
  . "$HOME/.cargo/env"
  CARGO="cargo +$MSRV"
fi

$CARGO run --quiet --package conform-web -- --root . --out website/dist
